# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Pipeline sẽ tự động chạy khi có push lên nhánh main

# --- SỬA Ở ĐÂY ---
# Chỉ định sử dụng agent pool tên là 'Default' (self-hosted agent của bạn)
pool: Default

steps:
- task: Maven@3
  displayName: 'Build with Maven' # Thêm displayName để log dễ đọc hơn
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17' # QUAN TRỌNG: Đảm bảo bạn đã cài JDK 17 trên máy tính chạy agent
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service' # Thêm displayName
  inputs:
    azureSubscription: 'AzureSubscriptionConnection'
    appType: 'webAppLinux'
    appName: 'webapp-trungnc19huutn'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'
    runtimeStack: 'JAVA|17-java17'